services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    mem_limit: 1g #limite máximo de memoria RAM
    mem_reservation: 512m #cantidad mínima de memoria reservada
    cpus: 1.0

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: node src/server.js
    deploy:
      replicas: 3